server:
  port: 8280

spring:
  datasource:
    # postgres driver needs to be configured if the cache is desired to be persisted in between server restarts
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy

weather-api:
  url: http://api.openweathermap.org/data/2.5/weather?q={city}&appid={appid}&units=metric
  id: enter_your_secret_id

coding-dojo:
  cache-data: 120 # in seconds